#################################################
CONFIG_NAME: 'formula-to-coord'

DATASET_NAME: 'mp_3d_2020'
DATA_DIR: './data/'

CUDA: True

CHECKPOINT_DIR: './checkpoints'
#################################################
GPU_ID: '0'
WORKERS: 12
#################################################
TRAIN:
  #################################################
  LAYERS: 4
  ATOM_INPUT_DIM: 92
  HIDDEN_DIM: 256
  OUTPUT_DIM: 1
  N_HEADS: 4
  NUM_TRAIN: 10
  NUM_VALID: 5
  NUM_TEST: 5

  MAX_EPOCH: 10
  BATCH_SIZE: 2
  SNAPSHOT_INTERVAL: 5
#################################################
# DO NOT CHANGE
TEST:
  B_EXAMPLE: False
  GENERATED_TEST_IMAGES: './evaluation/generated_images'
#################################################